name: quality
on:
  push: { branches: [ main, review/** ] }
  pull_request: { branches: [ main ] }
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -e . black isort ruff mypy bandit pip-audit pytest coverage
      - name: Lint
        run: |
          ruff check src
          black --check src
          isort --check-only src
      - name: Type-check
        run: mypy src
      - name: Security
        run: |
          bandit -r src -q
          pip-audit -q
      - name: Tests + Coverage
        run: |
          coverage run -m pytest -q
          coverage report --fail-under=70
